[phases.setup]
# Especificamos los paquetes de Nix para el entorno
nixPkgs = ["python3", "ffmpeg", "nodejs_20"]

[phases.install]
# Definimos explícitamente el comando de instalación
cmds = ["npm install"]

[phases.build]
# Si no necesitas compilar nada, podemos omitir o dejar vacía esta fase
cmds = []

[start]
# El comando para arrancar la aplicación
cmd = "node index.js"
